[project]
name = "gymnasium-rl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gymnasium==1.2.0",
    "loguru==0.7.3",
    "matplotlib==3.10.3",
    "numpy==2.3.1",
    "pygame==2.6.1",
]
